<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/09 15:44:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=divideme',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
