<?php
// auto-generated by sfViewConfigHandler
// date: 2015/08/09 15:44:02
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Divideme', false, false);
  $response->addMeta('description', 'Sitio para dividir cuentas grupales', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('charset', 'utf-8', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('jquery.min.js', '', array ());
  $response->addJavascript('jquery.dropotron.min.js', '', array ());
  $response->addJavascript('skel.min.js', '', array ());
  $response->addJavascript('skel-viewport.min.js', '', array ());
  $response->addJavascript('util.js', '', array ());
  $response->addJavascript('respond.min.js', '', array ());
  $response->addJavascript('main.js', '', array ());


